export const SquareStatus = {
  OPEN: "OPEN",
  SHIP: "SHIP",
  HIT: "HIT",
  MISS: "MISS"
};

export const ShipOrientation = {
  HORIZONTAL: "HORIZONTAL",
  VERTICAL: "VERTICAL"
};

export const Stages = {
  MENU: "MENU",
  PLACING_SHIPS: "PLACING_SHIPS",
  GAME: "GAME",
  DONE_PLACING_SHIPS: "DONE_PLACING_SHIPS",
  PLAYER_TURN_FINISHED: "PLAYER_TURN_FINISHED",
  GAME_FINISHED: "GAME_FINISHED"
};
